### ISSUE TITLE
Handoff doesn't work

### ISSUE THREAD

**Issue by LeLunZ** [Mieze/OS-X-BrcmPatchRAM-Catalina#2]
my system should support handoff but it currently doesn't work?
Do you have any idea why?

![Bildschirmfoto 2019-10-09 um 20 55 40](https://user-images.githubusercontent.com/31982496/66511416-2ddf7c00-ead7-11e9-9818-1238bcc7a44a.png)

Airdrop and Bluetooth is working very well! 
Also the take/insert photo from iPhone option in finder is grayed out.

**Comment by LeLunZ** [comment]
Got the info that iCloud logout and login helps.
Will try that later in the afternoon

**Comment by Hologos** [comment]
For handoff, there are usually other patches. For me personally, I have these in my `/Library/Extensions`
- AirportBrcmFixup.kext
- BT4LEContinuityFixup.kext

**Comment by LeLunZ** [comment]
> For handoff, there are usually other patches. For me personally, I have these in my `/Library/Extensions`
> 
> * AirportBrcmFixup.kext
> * BT4LEContinuityFixup.kext

Yeah I know, I also have them. In Mojave everything worked fine. But with your patches it somehow doesn't work anymore.
I tried login off/on in iCloud/Apple ID on my Mac.
But the problem still exist.
So next step is to log off/on in iCloud on my phone.

**Comment by Mieze** [comment]
This repository is obsolete.
