### ISSUE TITLE
Downloadable files

### ISSUE THREAD

**Issue by Hologos** [Mieze/OS-X-BrcmPatchRAM-Catalina#4]
Hi,

I found compiled files on insanelymac.com forum. It would be great if you posted files here on github as releases as well. I'd like to always get the latest version and it's better to check this repo than the forum thread.

Thank you

**Comment by Mieze** [comment]
This fork is obsolete as it has been merged into https://github.com/acidanthera/BrcmPatchRAM

There will be a new release soon which contains all of my changes.
